#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

GIT_SECRETS_PATH="/usr/local/bin/git-secrets"

if [ ! -x "$GIT_SECRETS_PATH'"]
# if ! command -v git-secrets &> /dev/null
then
  echo "git-secrets is not installed. Get better"
  exit 1
fi

git-secrets --register-aws > /dev/null

patterns="sk_live_[0-9a-zA-Z]{98} [0-9A-Za-z_]{32}\.apps\.googleusercontent\.com (-){5}\s*(BEGIN\sRSA\sPRIVATE\sKEY)\s*(-){5}"

log_file="git_secrets.log"

add_pattern_if_not_exists() {
  pattern="$1"

  existing_patterns=$(git secrets --list 2>>"$log_file")

  echo "pattern===" $pattern

  if echo "$existing_patterns" | grep -Fqe "$pattern"; then
    echo "Pattern '$pattern' already exists."
  else
    echo "Pattern '$pattern' not found. Adding.."

    git secrets --add "$pattern" 2>>"$log_file"

    if [ $? -eq 0 ]; then
      echo "Pattern '$pattern' added successfully."
    else 
      echo "Failed to add pattern: '$pattern'."
    fi
  fi
}

for pattern in $patterns; do
  add_pattern_if_not_exists "$pattern"
done

echo "Running git-secrets..."
git-secrets --scan -r

# git-secrets --pre_commit_hook -- "$0"

